"use strict";(self.webpackChunkvirtualclient=self.webpackChunkvirtualclient||[]).push([[541],{3905:(e,t,n)=>{n.d(t,{Zo:()=>c,kt:()=>u});var r=n(7294);function o(e,t,n){return t in e?Object.defineProperty(e,t,{value:n,enumerable:!0,configurable:!0,writable:!0}):e[t]=n,e}function i(e,t){var n=Object.keys(e);if(Object.getOwnPropertySymbols){var r=Object.getOwnPropertySymbols(e);t&&(r=r.filter((function(t){return Object.getOwnPropertyDescriptor(e,t).enumerable}))),n.push.apply(n,r)}return n}function a(e){for(var t=1;t<arguments.length;t++){var n=null!=arguments[t]?arguments[t]:{};t%2?i(Object(n),!0).forEach((function(t){o(e,t,n[t])})):Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(n)):i(Object(n)).forEach((function(t){Object.defineProperty(e,t,Object.getOwnPropertyDescriptor(n,t))}))}return e}function l(e,t){if(null==e)return{};var n,r,o=function(e,t){if(null==e)return{};var n,r,o={},i=Object.keys(e);for(r=0;r<i.length;r++)n=i[r],t.indexOf(n)>=0||(o[n]=e[n]);return o}(e,t);if(Object.getOwnPropertySymbols){var i=Object.getOwnPropertySymbols(e);for(r=0;r<i.length;r++)n=i[r],t.indexOf(n)>=0||Object.prototype.propertyIsEnumerable.call(e,n)&&(o[n]=e[n])}return o}var s=r.createContext({}),p=function(e){var t=r.useContext(s),n=t;return e&&(n="function"==typeof e?e(t):a(a({},t),e)),n},c=function(e){var t=p(e.components);return r.createElement(s.Provider,{value:t},e.children)},h={inlineCode:"code",wrapper:function(e){var t=e.children;return r.createElement(r.Fragment,{},t)}},d=r.forwardRef((function(e,t){var n=e.components,o=e.mdxType,i=e.originalType,s=e.parentName,c=l(e,["components","mdxType","originalType","parentName"]),d=p(n),u=o,m=d["".concat(s,".").concat(u)]||d[u]||h[u]||i;return n?r.createElement(m,a(a({ref:t},c),{},{components:n})):r.createElement(m,a({ref:t},c))}));function u(e,t){var n=arguments,o=t&&t.mdxType;if("string"==typeof e||o){var i=n.length,a=new Array(i);a[0]=d;var l={};for(var s in t)hasOwnProperty.call(t,s)&&(l[s]=t[s]);l.originalType=e,l.mdxType="string"==typeof e?e:o,a[1]=l;for(var p=2;p<i;p++)a[p]=n[p];return r.createElement.apply(null,a)}return r.createElement.apply(null,n)}d.displayName="MDXCreateElement"},6078:(e,t,n)=>{n.r(t),n.d(t,{assets:()=>s,contentTitle:()=>a,default:()=>h,frontMatter:()=>i,metadata:()=>l,toc:()=>p});var r=n(7462),o=(n(7294),n(3905));const i={},a="Error Handling",l={unversionedId:"developing/ErrorHandling",id:"developing/ErrorHandling",title:"Error Handling",description:"The following sections describe important details and recommendations for handling errors/exceptions in the operations of the",source:"@site/docs/developing/ErrorHandling.md",sourceDirName:"developing",slug:"/developing/ErrorHandling",permalink:"/docs/developing/ErrorHandling",draft:!1,editUrl:"https://github.com/microsoft/VirtualClient/docs/developing/ErrorHandling.md",tags:[],version:"current",frontMatter:{},sidebar:"tutorialSidebar",previous:{title:"Virtual Client Developer Guide",permalink:"/docs/developing/Developer-Guide"},next:{title:"Writing Virtual Client Extensions",permalink:"/docs/developing/VC-Extensions"}},s={},p=[{value:"VirtualClientException",id:"virtualclientexception",level:2},{value:"Exception Handling",id:"exception-handling",level:2},{value:"Exception Handling Recommendations",id:"exception-handling-recommendations",level:2}],c={toc:p};function h(e){let{components:t,...n}=e;return(0,o.kt)("wrapper",(0,r.Z)({},c,n,{components:t,mdxType:"MDXLayout"}),(0,o.kt)("h1",{id:"error-handling"},"Error Handling"),(0,o.kt)("p",null,"The following sections describe important details and recommendations for handling errors/exceptions in the operations of the\nVirtual Client runtime. Error handling is particularly important for the quality of a runtime platform where there are many moving\nparts."),(0,o.kt)("h2",{id:"virtualclientexception"},"VirtualClientException"),(0,o.kt)("p",null,"The Virtual Client platform/core contains a base class that is used for most exceptions that are explicitly raised/thrown in the application\nnamed ",(0,o.kt)("strong",{parentName:"p"},"VirtualClientException"),". This exception class derives from the .NET framework 'Exception' class and allows the developer to communicate\nnot only a description of the error but also a structured \"reason\" for the error. The profile execution logic makes determinations on the severity\nof exceptions that are raised/thrown based on the data type of the exception as well as the error reason that is supplied."),(0,o.kt)("ul",null,(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("a",{parentName:"li",href:"https://github.com/Azure/AzureVirtualClient/blob/main/src/VirtualClient/VirtualClient.Contracts/Exceptions.cs"},"Custom Platform/Core Exceptions"),"  "),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("a",{parentName:"li",href:"https://github.com/Azure/AzureVirtualClient/blob/main/src/VirtualClient/VirtualClient.Contracts/Enumerations.cs"},"Error Reasons"),"  "),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("a",{parentName:"li",href:"https://github.com/Azure/AzureVirtualClient/blob/main/src/VirtualClient/VirtualClient.Core/ProfileExecutor.cs"},"Profile Execution Logic"))),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-csharp"},"// Custom exception classes in the Virtual Client platform/core derive from the base VirtualClientException class. Each of the\n// platform/core exception classes implement the same constructors for consisteny. The 'ErrorReason' provided is an important distinction.\npublic class WorkloadException : VirtualClientException\n{\n    public WorkloadException()\n        : base()\n    {\n    }\n\n    public WorkloadException(string message)\n        : base(message)\n    {\n    }\n\n    public WorkloadException(string message, ErrorReason reason)\n        : base(message, reason)\n    {\n    }\n\n    public WorkloadException(string message, Exception innerException)\n        : base(message, innerException)\n    {\n    }\n\n    public WorkloadException(string message, Exception innerException, ErrorReason reason)\n        : base(message, innerException, reason)\n    {\n    }\n}\n\n// Errors raised during the operations of the hosted REST API service.\nthrow new ApiException();\n\n// Errors raised during the operations of a dependency installer/handler.\nthrow new DependencyException();\n\n// Errors raised during the operations of a monitor.\nthrow new MonitorException();\n\n// Errors raised during the operations of a workload/test.\nthrow new WorkloadException();\n\n// Errors raised during the operations of parsing the results of a workload/test.\nthrow new WorkloadResultsException();\n")),(0,o.kt)("h2",{id:"exception-handling"},"Exception Handling"),(0,o.kt)("p",null,"Based upon the data type of the exception thrown as well as the 'ErrorReason' (if it is one of the custom platform/core exceptions), the profile execution\nlogic makes a decision on whether to handle it or let the Virtual Client crash. Thus error handling in the Virtual Client is a fair amount methodical and there\nare recommendations as to how exceptions should be handled and thrown/raised. The type and severity of exceptions that are raised are at the discretion of the\ndeveloper that implements them. The specifics of the nature of errors can only be known in the context of the component a developer implements. The developer\ncan communicate error handling intent to the profile execution that is relevant. There are recommendations in sections that follow."),(0,o.kt)("p",null,"The following sections explain some of the methodology around exception handling in the Virtual Client."),(0,o.kt)("ul",null,(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"Exceptions that are not explicitly handled by the profile execution logic result in a crash"),(0,o.kt)("br",{parentName:"p"}),"\n","The profile execution logic handles a few different exception types. However, if an exception is not a part of that explicit list of exceptions, the Virtual Client\nruntime application will crash.")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"VirtualClientException instances with error reasons from 100 - 399 are considered transient"),(0,o.kt)("br",{parentName:"p"}),"\n","Exceptions with an ErrorReason value from 100 - 399 are considered transient and will be handled. Transient errors are those in which the\ndeveloper has indicated the error will very likely go away within a period of time and thus the runtime operations will begin succeeding as expected. Exceptions\nof this type will not crash the Virtual Client. The profile execution logic will continue onward. For example, if a particular workload execution action in a\nprofile happened to fail, the profile execution logic would continue on to the next action.")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"VirtualClientException instances with error reasons from 400 - 499 represent critical failures that cannot be confirmed as transient or not"),(0,o.kt)("br",{parentName:"p"}),"\n","Exceptions with an ErrorReason value from 400 - 499 represent highly disruptive failures to the operations of the Virtual Client. However, they may or may not be\ntransient. That determination is not clear. It is this distinction (the fact that we cannot know if it is transient) why the profile execution logic generally handles\nexceptions of this type and continue onward.")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"VirtualClientException instances with error reasons >= 500 represent terminal/permanent failures"),(0,o.kt)("br",{parentName:"p"}),"\n","Exceptions with an ErrorReason value greater than or equal to 500 represent terminal failures. These are failures where it is generally know that the Virtual Client\ncould never recover from them. For example the user supplied the name of a profile on the command line that does not exist. In this case, the profile file does not exist\nand thus the Virtual Client could never know what it was supposed to do. Exceptions of this type will crash the Virtual Client."))),(0,o.kt)("h2",{id:"exception-handling-recommendations"},"Exception Handling Recommendations"),(0,o.kt)("p",null,"The following sections document recommendations for the developer to follow when implementing new components in the Virtual Client codebase."),(0,o.kt)("ul",null,(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"Explicitly handle known exceptions"),(0,o.kt)("br",{parentName:"p"}),"\n","As a general rule, all known exceptions should be handled and dealt with appropriately. The developer should make a decision depending upon the type of exception\nwhether it should then be propagated further. Exceptions that are not handled in an individual component will almost always crash the Virtual Client application.\nThis is by design.")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"Retry on transient errors"),(0,o.kt)("br",{parentName:"p"}),"\n","For many cases of transient errors, a simple set of retries is enough to recover. Retries on transient error situations can be one of the best ways to build\nreliability into an application. The Virtual Client codebase leverages an open source .NET framework called 'Polly' to implement retry handling logic in\na consistent manner. The framework is already a part of the Virtual Client platform/core projects and libraries."),(0,o.kt)("ul",{parentName:"li"},(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("a",{parentName:"li",href:"http://www.thepollyproject.org/"},"Polly Transient Fault Handling Library")))),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"Always provide good context-specific information in exceptions raised/thrown"),(0,o.kt)("br",{parentName:"p"}),"\n","Regardless of the quality of a software application, errors will always occur given time and certain scenarios. Error handling is always a challenging thing to\ndo well in any application; however, one of the key most important things to ensure is that the information provided in an error/exception is clear. Few things\nare worse than having to figure out why an application is failing and having very little information by which to do so. When developing components in the Virtual\nClient codebase, take the time to provide good information in error messages. Provide any amount of context information that is available in the code at the point\nof throwing the exception that would help another person (including users and folks that do not program) understand what has happened. Sometimes a quality error enables\na user to course-correct. Otherwise, the user will likely be reaching out to the team and making it the someone on your team's problem instead. Lots of time is\nwasted in this way."),(0,o.kt)("pre",{parentName:"li"},(0,o.kt)("code",{parentName:"pre",className:"language-csharp"},'try\n{\n    ...\n}\ncatch (FileNotFoundException exc)\n{\n    // This is an example of an error which is not very good. What file was not found?!! There will likely be more\n    // than 1 file involved in running a particular Virtual Client profile. Give the user some pertinent information\n    // about the situation so that they might be able to do something intelligent about it.\n    throw new WorkloadException("The file was not found.", exc);\n\n    // This is an example of better error information. The user might be able to address this on his/her own without need\n    // for extra assistance. That is more satisfying for the user (who can self-help) as well as for the team.\n    throw new WorkloadException(\n        $"The expected script file \'{scriptFile}\' was not found in the workload package with the name \'{this.PackageName}\'. " +\n        $"This script is used to parse the custom results from the workload.",\n        exc);\n}\n'))),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"Define an appropriate 'ErrorReason' when raising/throwing exceptions that indicate transient errors"),(0,o.kt)("br",{parentName:"p"}),"\n","If an exception is caught within a given component that is deemed to be transient (despite any retries attempted), the exception thrown should be one of the\ntypes that derive from the 'VirtualClientException' class. Additionally an appropriate 'ErrorReason' should be supplied indicating the category and severity of\nthe error so that the profile execution logic can itself handle it appropriately. Transient error reasons are in the range of 100 - 399. If an appropriate reason\ndoes not already exist on the 'ErrorReason' enumeration, create one."),(0,o.kt)("pre",{parentName:"li"},(0,o.kt)("code",{parentName:"pre",className:"language-csharp"},"try\n{\n    ...\n}\ncatch (FileNotFoundException exc)\n{\n    // ErrorReason.WorkloadResultsNotFound = 314\n\n    throw new WorkloadException(\n      $\"The '{workloadName}' workload experienced an issue writing the results file to the system.\",\n      exc,\n      ErrorReason.WorkloadResultsNotFound);\n}\n"))),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"Define an appropriate 'ErrorReason' when raising/throwing exceptions that indicate terminal/permanent errors"),(0,o.kt)("br",{parentName:"p"}),"\n","If an exception is caught within a given component that is deemed to be transient (despite any retries attempted), the exception thrown should be one of the\ntypes that derive from the 'VirtualClientException' class. Additionally an appropriate 'ErrorReason' should be supplied indicating the category and severity of\nthe error so that the profile execution logic can itself handle it appropriately. Transient error reasons are in the range of 100 - 399. If an appropriate reason\ndoes not already exist on the 'ErrorReason' enumeration, create one."),(0,o.kt)("pre",{parentName:"li"},(0,o.kt)("code",{parentName:"pre",className:"language-csharp"},"try\n{\n    ...\n}\ncatch (FileNotFoundException exc)\n{\n    // ErrorReason.ProfileNotFound = 500\n\n    throw new DependencyException(\n      $\"A profile '{profileName}' does not exist on the file system by this name or path provided.\",\n      exc,\n      ErrorReason.ProfileNotFound);\n}\n"))),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"Always include the original exception when raising/throwing another/custom type of exception"),(0,o.kt)("br",{parentName:"p"}),"\n","If an exception is caught within a given component and the developer chooses to propagate it by throwing an exception of a different\ntype, the original exception should be included in the new exception instance."),(0,o.kt)("pre",{parentName:"li"},(0,o.kt)("code",{parentName:"pre",className:"language-csharp"},"try\n{\n    // Some logic here that is looking for a specific file on the file system.\n    string script = this.systemManagement.FileSystem.File.ReadAllText(filePath);\n}\ncatch (FileNotFoundException exc)\n{\n    throw new WorkloadException(\n        $\"The expected workload script '{filePath}' does not exist on the file system.\",\n        exc,\n        ErrorReason.DependencyNotFound);\n}\n")))))}h.isMDXComponent=!0}}]);